name: CD-external

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 3

jobs:
  dist:
    name: External Indices
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install db-dtypes google-cloud-bigquery pandas pyarrow

      - name: Authorize Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"
          create_credentials_file: true
          export_environment_variables: true

      - name: Execute SQL Query and Generate Parquet Files
        run: |
          python scripts/python/external-indices.py
        env:
          PROJECT_ID: ${{ env.GCP_PROJECT }}

      - name: Create Tagged Release
        id: create_tagged_release
        if:
          (startsWith(github.ref, 'refs/tags/v') && github.event_name !=
          'pull_request')
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          artifacts: "*.parquet"
